import utils
import argparse
import numpy as np


def compute_distinct_metric(sentence, n):
    """
    Compute distinct-N for a single sentence.
    :param sentence: string, words separated by space.
    :param n: int, ngram.
    :return: float, the metric value.
    """
    sentence = sentence.strip().split(" ")
    if not sentence:
        return 0.0  # Prevent a zero division
    distinct_ngrams = set(utils.ngrams(sentence, n))
    return len(distinct_ngrams) / len(sentence)


def distinct_score(infile, n):
    """
    Compute distinct-N on a response file.
    :param infile: string, responses generated by the model. Each response is on its own line.
    :param n: int, ngrams.
    :return:
    """
    with open(infile, 'r') as f:
        # Compute metric for each line of a file.
        scores = [compute_distinct_metric(sentence, n) for sentence in f.readlines()]
    scores = np.asarray(scores)
    return np.mean(scores), 1.96 * np.std(scores) / len(scores), np.std(scores)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('predicted', help="predicted text file, one example per line")
    parser.add_argument('-n', type=int, default=2, help="n to use as in distinct-N")
    args = parser.parse_args()

    r = distinct_score(args.predicted, args.n)
    print("Distinct-%d: %f +/- %f ( %f )" % (args.n, r[0], r[1], r[2]))
